version: '3.5'

services:
  symfony-app:
    container_name: symfony-app
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=symfony-server
    ports:
      - '8000:80'
    networks:
      - symfony-app-network
    depends_on:
      - symfony-app-pgsql

  symfony-app-pgsql:
    container_name: symfony-app-pgsql
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=url-shortener
    volumes:
      - symfony-app-pgsql-data:/var/lib/mysql
    networks:
      - symfony-app-network

networks:
  symfony-app-network:

volumes:
  symfony-app-pgsql-data:
